language: node_js
sudo: required
services:
        - docker
before_install:
        - docker build -t mohgamalmoh/react-test -f ./client/Dockerfile.dev ./client
           
script:
        - docker run -e CI=true mohgamalmoh/react-test npm run test

after_success:
        - docker build -t mohgamalmoh/multi-client ./client
        - docker build -t mohgamalmoh/multi-nginx ./nginx
        - docker build -t mohgamalmoh/multi-server ./server
        - docker build -t mohgamalmoh/multi-worker ./worker
        #docker cli login through travis
        - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
        #push to hub
        - docker push mohgamalmoh/multi-client
        - docker push mohgamalmoh/multi-nginx
        - docker push mohgamalmoh/multi-server
        - docker push mohgamalmoh/multi-worker

deploy:
        provider: elasticbeanstalk
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-1-722072946654
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY
